name: Unit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
        scope: '@trapize:registry=https://npm.pkg.github.com'
    - run: npm install 2>&1
      env:
        NODE_AUTH_TOKEN: ${{}}
    - run: npm run build --if-present
    - run: npm run lint --if-present
    - run: npm test
      env:
        CI: true
    - name: Upload npm error
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: 'npm_log'
        path: '/home/runner/.npm/_logs'
    
